//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public int MaBaiViet { get; set; }
        public string TenBaiViet { get; set; }
        public string NoiDungBaiViet { get; set; }
        public Nullable<System.DateTime> NgayViet { get; set; }
        public Nullable<int> MaDanhMucBaiViet { get; set; }
    
        public virtual DanhMucBaiViet DanhMucBaiViet { get; set; }
    }
}
